### ISSUE TITLE
Attempting to run a macro multiple times does not work if you press Enter instead of pressing the OK button.

### ISSUE THREAD

**Issue by ergins23** [Microsoft/VS-Macros#18]
I pressed the button to run a macro multiple times, the small dialog shows up asking me to enter the number of times the macro should be executed.  I entered a number an pressed **Enter** to confirm, the macro did not execute at all but the macro explorer showed that the macro was running (the **run** button changed to a **stop** button).

If I do the same thing but press the **OK** button everything works as expected.

**Comment by justcla** [comment]
Hi ergins23

I've looked in to this but can't seem to replicate it.
Can you please provide more detail about the steps taken to reproduce this?
Which version of VS are you using?
Which macro are you running?
Are you pressing the button on the marco explorer or through the menu.
Does it happen if you record a simple macro (like insert text)?
And anything else you think might help to replicate this issue.

Thanks

**Comment by ergins23** [comment]
justcla, 
Thanks for looking into this, I just upgraded to 1.21 and tried the same thing and it looks like it is working now.
Best regards
ergins23

**Comment by justcla** [comment]
OK. That's great. Good to hear.
