### ISSUE TITLE
Tools.MacroCommand# was not added to the list of possible commands for key assignment

### ISSUE THREAD

**Issue by scotthbradley** [Microsoft/VS-Macros#19]
Unfortunately my install of this extension did not add the Tools.MacroCommand# to my VS2015 instance, so I cannot assign custom keystrokes to my macros.  

I have installed, uninstalled and re-installed, restarting each time, without the Tools.MacroCommand list added to the list of keyboard commands...

My visual studio version reports this version info for my instance.
  Microsoft Visual Studio Enterprise 2015
  Version 14.0.24720.00 Update 1
  Microsoft .NET Framework
  Version 4.6.01055

Also, how do you assign a number to a command to use with key assignment? I tried assigning it by assigning the preset command keyboard shortcut of <CTRL-M>1 or <CTRL-M>2, but no other way exists that I can see to assign a number...  

(...by the way, I love the fact that you guys used Javascript as your language of choice... It is my absolute favorite scripting language!!!)

**Comment by Puresoft** [comment]
Have the same same problem. Tools.Macro* does not appear in the list of commands.

**Comment by justcla** [comment]
Fixed in version 1.2.1

Pre-defined macro commands now appear on the Tools->Macros menu.
And all 9 MacroCommands are now available for keyboard assignment in Tools->Options (Keyboard)
