### ISSUE TITLE
'stdole' assembly could not load on every action taken in Macro Explorer

### ISSUE THREAD

**Issue by jakubsuchybio** [Microsoft/VS-Macros#31]
![image](https://cloud.githubusercontent.com/assets/6567287/16518941/15e0ffa2-3f86-11e6-90a5-360d824a3aa2.png)

**Comment by justcla** [comment]
Hi Jakub
What version (and update) of Visual Studio are you running?
Does this error occur reliably every time?
What is the macro code that is triggering this bug? (Would you mind sharing the Macro code?)
Justin

**Comment by timsneath** [comment]
Hi Jakub, by any chance are you on the Windows Insiders program? If so, what build of Windows 10 are you running? 

And can you check whether the file \Program Files (x86)\microsoft.net\Primary Interop Assemblies\stdole.dll exists on your machine? 

We've seen a few instances recently where stdole.dll either got deleted or removed during build-to-build upgrades. Depending on your answer, I have a few potential solutions for you...

**Comment by jakubsuchybio** [comment]
- Version of VS in the picture
- Yes error pops-up everytime, however it seems, that when I hit Record, it pops up, but it is still started Recording, also with other actions it seems
- It doesn't do the macro code, but anything really I touch in Macro Explorer
- Yes I am Windows insider - version in picture
- Yes file exists, details in picture
![image](https://cloud.githubusercontent.com/assets/6567287/16537249/19910034-3ffe-11e6-8c8c-e5f03863152a.png)

**Comment by timsneath** [comment]
Thanks! Can you try running `gacutil -i "%ProgramFiles(x86)%\Microsoft.NET\Primary Interop Assemblies\stdole.dll"` and then relaunch Visual Studio?

**Comment by jakubsuchybio** [comment]
Yep that fixed it. However your path didn't work, so I had to put there absolute one.
Thanks!
Just for future uses:
- Open cmd with admin privileges
```
cd c:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\
./gacutil.exe -i "c:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies\stdole.dll"
```
This ```v10.0A\bin\NETFX 4.6 Tools\``` can be something else (other versions)

**Comment by timsneath** [comment]
Glad it fixed it, Jakub. Thanks for reporting back.
