### ISSUE TITLE
Error "Could not find a part of the path"

### ISSUE THREAD

**Issue by xyzzer** [Microsoft/VS-Macros#7]
When I try to record a macro after installing I get this dialog:

Could not find a part of the path 'C:\Users\filips\AppData\Local\Microsoft\VisualStudio\14.0\Macros\Macros\Current.js'.

It turns out that indeed - there is no Macros\Macros folder under C:\Users\filips\AppData\Local\Microsoft\VisualStudio\14.0\

Creating the two subfolders seems to fix the problem.

**Comment by justcla** [comment]
This is a known issue. Contributions welcome. Thanks!

**Comment by justcla** [comment]
When the Macro Explorer opens for the first time, it creates those folders (and copies the samples there).

So a good workaround is to open the Macro Explorer first.

**Comment by justcla** [comment]
Fixed in pull request #13

**Comment by justcla** [comment]
Fixed in version 1.2.0
